### ISSUE TITLE
Page Fault and General Protection Fault in Round-Robin Scheduler with Stack Allocation

### ISSUE THREAD

**Issue by IlanVinograd** [IlanVinograd/OS_32Bit#47] opened 2024-11-07 20:35 UTC
@mpetch Hi, could you take a look at the code in the "target" branch? I'm working on a simple round-robin scheduler with context switching every 10 ms. I initially set each task’s stack to 4096 bytes (1 page), but I was getting a page fault. When I increased the stack size to 2 pages, it started giving me a general protection fault instead.

I’ve double-checked the sp and pc values for all tasks, and they seem fine, but I still can’t pinpoint the source of the issue. Any advice on where I might be going wrong or what else I should check would be really appreciated!

Thanks for your help!

**With 1 page allocated for the stack (resulting in a page fault):**
![Page fault](https://github.com/user-attachments/assets/ad0129e8-b255-4dfa-9d1f-2d6628f50295)

**With 2 pages allocated for the stack (leading to a general protection fault and some strange behavior with the page counter):**
![Page fault 2](https://github.com/user-attachments/assets/1065d715-0a1e-4133-97ab-cbec2ceb96b5)

**Comment by mpetch** [comment] 2024-11-08 01:13
When I get a chance this weekend I can take a look.

**Comment by IlanVinograd** [comment] 2024-11-09 07:19
Thank you for your help.

**Comment by mpetch** [comment] 2024-11-10 01:11
I can tell you why, but to fix it requires a whole rethink of your scheduling. As it is you only ever allow a single timer interrupt to occur. The `pit_handler` eventually calls `schedule` that jumps into the next task and never returns (and never gets a chance to send an EOI nor does an IRET to enable external interrupts again). The reason it never returns is you jmp into the next task that calls `yield` which does an `int $0x20` to call the `irq0` and then `pit_handler` which jumps to the next task but again doesn't itself exit but calls `yield`. Every `int $0x20` pushes more data on the stack until you blow past the end of the stack where weird and wonderful things happen (what happens isn't defined behaviour). Basically you are recursively calling `int $020` until the stack blows up (overflows).

I also noticed you attempted to update `esp0` in the TSS. Please be aware that when running in ring0 the stack doesn't change to what is in esp0 of the TSS when an interrupt occurs. That only happens if the interrupt occurs while running outside kernel mode in (ring 1-3). 

Although you set up a stack for each task on the heap, one of the tasks will end up using the kernel stack that was set in kernel_entry.s . This is because your scheduler really doesn't track the stack properly. Your task switching doesn't even preserve the general purpose registers when trying to switch.

**Comment by IlanVinograd** [comment] 2024-11-10 05:50
@mpetch  Thank you very much for the response; I understand where the issue with the scheduler lies now, but I have one question. What values need to be saved for a process to switch to the next one? I initially used only the PC and SP, but I’m not quite sure how to handle the other registers—where and how should I use them? And a second question: before starting the scheduler itself, should I save my esp0 and all other values, including the registers, into a struct so that after returning from the scheduler, I can restore all pointers back to esp0 and continue with the main code, switching like this. Here's a rough example of what I mean:

```
struct main_ctx {
    // This is the default struct for main pointers like esp0, eip0, etc.
to be able return to main stack pointer and continue the rest of the code.
};

   
esp0 -> pid 1 -> esp0 -> pid 2 -> esp0 -> pid 1 
    // ...and so on, until the end of the program.
and then
esp0 = main_ctx -> esp0;

// continue execute the rest of the code.
```

Using TSS is only for transitioning between ring0 and ring3, and vice versa, but I thought it could be used for context switching. Thank you, I didn’t know that.

**Comment by mpetch** [comment] 2024-11-10 20:10
I thought you may have been trying to use the TSS for the purpose of context switching between different ring 0 tasks. As you now know you can't do it that way. Well, yes you can but you'd need to use hardware task switching and set up task gates. You do not want to go down that route. Hardware task switching is not very efficient and it doesn't migrate well to other architectures (like arm etc). A minimal amount of hardware task switching has its place but not for this.

The first thing I would do is take 2 steps back and go back to just getting co-operative multitasking working *properly*. In basic cooperative multitasking each kernel process (task) will have its own stack and all task switching will go through an assembly function using the C calling convention (and ABI). Let us call that `switch_to_task` (it takes a parameter - a pointer to the next task). Remove the call to `schedule` in your `pit_handler` since we aren't going to be doing preemptive multitasking (yet). `yield` can be changed to just calling `schedule`.

In cooperative multitasking eventually each task is going to stop when eventually it calls (through `yield` as an example) the `switch_to_task` function. This function will save the registers on the stack, save the current `ESP` to the current_task, and then change `ESP` to that of the next task. It will then restore the registers from the new tasks stack and return to the EIP of the task we switched to. While `switch_to_task` can push all registers onto the stack, it only really needs to push 4 of them:  `EBX` `ESI` `EDI` and `EBP`. This is because in the 32-bit C calling convention these 4 registers (and ESP) need to be preserved in a function, and the rest the caller will expect to be destroyed so we don't need to save them.

Brendan has an example of this in his multitasking tutorial which you might want to look at: https://wiki.osdev.org/Brendan%27s_Multi-tasking_Tutorial . In particular `switch_to_task`. It would have to me modified to work with your PCB structure (the offsets into the PCB will have to be set for your structure). Brendan doesn't provide complete code, just a basic template you can modify. You don't even need to do use the CR3 code in Brendan's example if CR3 will always be the same for each task. That simplifies the function. **Note: You may wish to read through Brendan's multitasking tutorial as it is a source of useful information.**

**Whatever you do, do not try to use inline assembly for task switching!!** . You don't know the state of the processor when running the inline assembly and it causes needless sources of potential bugs. Do your task switch (ESP switch) inside an assembly language function.

If you are having troubles getting basic cooperative multitasking going I can see about helping you out with that if you get stuck. Once you get the cooperative multitasking working then you can move onto getting preemptive multitasking working.

**Comment by IlanVinograd** [comment] 2024-11-15 14:12
Oh, I didn't see your pull request initially, and I went ahead and implemented everything for preemptive multitasking myself. However, I encountered issues with the `switch.asm` file for task switching. You can check my implementation in the `develop` branch.

Later, I noticed your pull request and tried your changes in the `target branch`. Unfortunately, I am still encountering a page fault there as well with cooperative multitasking:

![image](https://github.com/user-attachments/assets/1ddef306-48cd-4b84-add8-8ceb5f31aa68)

**Comment by IlanVinograd** [comment] 2024-11-15 14:29
It seems like the page fault is happening because `task1` ends, and then there are two tasks: the main code and the second test code. However, the second test does not print "Finished" as expected, while the first test does.

Here is a screenshot for reference:

![image](https://github.com/user-attachments/assets/34a52cd2-b68d-46c6-adc4-eb6e037aa59f)

**Comment by IlanVinograd** [comment] 2024-11-15 14:54
It seems that when one task finishes, the switch_task function, probably during the last yield() call, returns to this task after completing the cycle. However, it doesn't switch back to the other tasks, and it goes out of bounds, causing a page fault.

**Comment by mpetch** [comment] 2024-11-15 23:48
At this point which branch of yours should I be looking at? `develop`? Make sure you've put away your latest and let me know which branch. If it is the `develop` branch - I see a number of issues. I won't be able to look at it more thoroughly until later tonight or tomorrow.

As well can you download and build this version:  https://github.com/mpetch/OS_32Bit/archive/refs/tags/mpetch-coopmulti.tar.gz . I just want to know if that version worked for you? That is a version based strictly on my code.

**Comment by IlanVinograd** [comment] 2024-11-16 12:41
I am currently working on the `target` branch:

- I have added Preemptive Multitasking.

- I fixed the memory leakage in the task stacks using the following line:
`free((uintptr_t *)(task_terminate->fsp - STACK_SIZE));`

- I have added sti in the end of switch_to_task().

Before you had pushed the `tasksw.asm` file, I had attempted to implement context switching in the `develop` branch based on Brandon's tutorial to create the `switch.asm` file. However, it didn’t work.

The version available at:
https://github.com/mpetch/OS_32Bit/archive/refs/tags/mpetch-coopmulti.tar.gz works but has memory leakage when `remove(task)` is used in the code. It doesn’t free the task stacks.

The problems I am encountering in `target` branch are:

Yield() Requirement:
Is it necessary to always call yield() in tasks to avoid a page fault? When a task ends, the IRQ0 PIT doesn’t fire in time, causing esp0 to go beyond the task code and trigger a page fault. Is there a better way to handle this?

Critical Section Handling:
Do I need to use cli and sti every time I perform a critical operation, such as printing to the screen, to prevent the PIT from firing before the operation is completed? Is there an alternative or a best practice for managing this?

**Comment by IlanVinograd** [comment] 2024-11-16 13:55
Why does your code have two occurrences of printing DONE—one at the end of the kernel.c code and the other in the idle_task—but only the first DONE is used?
Additionally, why is the idle_task not used at all in the scheduler?

**Comment by mpetch** [comment] 2024-11-16 15:59
My code didn't have an `idle_task` at all, nor did it print `DONE` more than once. The issue is that you merged some of your `target` code on top of the `feature_target_coopmulti` branch that I created. You did that merge here:  https://github.com/mpetch/OS_32Bit/commit/fce9fc756da0659d2bc3f8e3122622d322f4f80c . It is the reason why I had to create a tag of my code. The actual code I had before you merged your stuff into it is here in this tag: https://github.com/mpetch/OS_32Bit/releases/tag/mpetch-coopmulti . That is the code you should be looking at. 

I didn't call `kfree` in `remove_task` because I wasn't aware you had a `kfree`. Adding `kfree` of the stack space is a simple fix.

**Comment by IlanVinograd** [comment] 2024-11-16 16:21
Oh, that was an accident. I didn’t mean to do that, and I didn’t even notice it. I’m sorry for the confusion caused. I checked the code you shared with me, and it works on my side.

**Comment by mpetch** [comment] 2024-11-16 16:26
No problem. I just finished reverting all your changes to my `feature_target_coopmulti` branch at https://github.com/mpetch/OS_32Bit/tree/feature_target_coopmulti in my repository.

**Comment by mpetch** [comment] 2024-11-16 17:07
Before I start doing anything, I need to ask. Did you ever get a cooperative multitasking version going that works properly? If so is it available? I'd like to make sure you can get cooperative multitasking first before even trying to implement preemptive. The preemptive version can build on the cooperative version, but if cooperative is broken then it rather fruitless to work on a preemptive version. I noticed at one point you had code that looks like this:

```
section .text
global switch_to_task_handler

switch_to_task_handler:
    cli                       ; Disable interrupts
    push ebx
    push esi
    push edi
    push ebp

    ; Save current task's stack pointer
    mov [esi + 12], esp       ; Store ESP into the current task's PCB

    ; Load next task's stack pointer
    mov esp, [edi + 12]       ; Load ESP from the next task's PCB

    ; Restore callee-saved registers
    pop ebp
    pop edi
    pop esi
    pop ebx

    sti                       ; Enable interrupts
    jmp [edi + 8]             ; Load EIP from the next task's PCB and jump to it
```
This is very broken code. `ESI` and `EDI` aren't guaranteed to be values of the pointers you expect (current and next). Parameters are passed on the stack in 32-bit code by default. As well the `jmp` instruction suggests to me this kind of code is going to blow up the stack in a similar fashion as I explained previously. The idea of using `jmp` to do the task switch won't work like this. I have a feeling you may have a flawed understanding of what Brendan's code/ideas does.

The idea in `switch_to_task_handler` is to save the required registers on the current stack, switch to the next stack and then restore the registers from the next stack and then return to the scheduler using the next stack. Eventually you return back to whoever called the scheduler where it continues.

**Comment by IlanVinograd** [comment] 2024-11-16 17:20
My code in the develop branch is not functional; this was my first attempt to create a file for context switching named switch.asm, but it didn’t work out. Right now, I’m thoroughly studying a Brandon's tutorial to understand how to create this file and grasp its logic. For cooperative multitasking, I used your tasksw.asm file as a base. Once cooperative multitasking was completed, I modified it and added a PIT to trigger every 10ms and call schedule(), enabling preemptive multitasking. This can be seen in the target branch.

**Comment by mpetch** [comment] 2024-11-16 18:57
Okay, I must have still been looking at the `develop` branch. Sorry about that. I can see what you've done now with my code in the `feature/target` branch. I will commit some small tweaks in the next hour that won't solve all your problems but will be a slight improvement which includes fixing the issue mentioned below. There is a fair amount of work that needs to be done to get it all working, but we need to start somewhere.

Word of caution. If you add/remove/change something to the `struct task` in PCB.h you need to modify tasksw.asm `struc PCB` to at least make sure the fields are all in the same order (the names of the fields don't have to match but size and location do). `struc PCB` is used to compute offsets into the task structure you use in C. If they don't match strange things could happen.

**Comment by mpetch** [comment] 2024-11-16 19:52
I have made a pull request for some changes: https://github.com/IlanVinograd/OS_32Bit/pull/51 . You can merge this, but be aware it will still blow up when run. I am trying to fix some basics but there is much to do to get this working. I have to go out for a few hours but will see about doing further work then.

**Comment by IlanVinograd** [comment] 2024-11-16 19:58
Your knowledge about OS development is truly impressive! I’m curious—how did you acquire such a deep understanding of these concepts? Did you learn it through personal projects, specific resources, or perhaps from formal education? I'd really appreciate hearing about your journey, as it could be incredibly inspiring and helpful for someone like me diving deeper into OS development.

**Comment by mpetch** [comment] 2024-11-16 22:56
My last commit hours ago had a major bug in it regarding the stack setup in PCB.c that I inadvertently introduced. I have made a pull request with that fix and a number of other enhancements at Pull https://github.com/IlanVinograd/OS_32Bit/pull/53 . This isn't complete but you should be able to get further. See the pull request for additional details of what I changed. Tomorrow when I get a chance I'll see about improving your interrupt handlers.

Regarding the cursor, you could for the time being save its state and restore it when you do a task switch in the scheduler. It may not be clean but it should work. I had noticed you may have considered this in a previous comment, I am just responding late to that.

**Closed as completed** 2024-11-21 10:01 UTC
Labels: bug, help wanted, question
